<font size = 8> Vectors

***

# Vectors (Rank1 Tensors) in Numpy

***

In [1]:
import numpy as np

In [2]:
# Use Numpy array method
# we specify scalar values in the array[]

x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16

x

array([25,  2,  5])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0] # zero-indexed

25

In [7]:
x[1]

2

In [8]:
x[2]

5

In [9]:
type(x[0])

# you could have also optionally created these as 16 bit floats
# default is 64 bit integers

numpy.int64

***

# Vector Transposition

***

In [10]:
# Transposing a regular 1-D array has no effect...
# the .T will do the trick

x_t = x.T

x_t

# it appears to have the same shape as x did

# that is because this is a 1 dimentional array and there is no second dimention to be 
# trasnposed into

array([25,  2,  5])

In [11]:
x_t.shape

(3,)

In [12]:
# ...but it does we use nested "matrix-style" brackets: 

# the nested brackets indicate two dimensions

y = np.array([[25, 2, 5]])

y

array([[25,  2,  5]])

In [13]:
y.shape

(1, 3)

In [ ]:
## this shows 1 row and 3 columns

In [14]:
# ...but can transpose a matrix with a dimension of length 1, 
# which is mathematically equivalent: 
y_t = y.T

y_t

array([[25],
       [ 2],
       [ 5]])

In [15]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [29]:
# now this has 3 rows and 1 column

***

In [30]:
# transposing it back to the original row vector

In [16]:
# Column vector can be transposed back to original row vector: 
y_t.T 

array([[25,  2,  5]])

In [17]:
y_t.T.shape

(1, 3)

***

# Zero Vectors

***

In [18]:
# These are contained entirely of 0s
# created by the np.zeros method

z = np.zeros(3) 

z

array([0., 0., 0.])

***

# Vectors in PyTorch

In [1]:
import torch

In [2]:
x_pt = torch.tensor([25, 2, 5])

x_pt

tensor([25,  2,  5])

***

# Vectors in TensorFlow

***

In [3]:
import tensorflow as tf

In [5]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>