<font size = 8> TBD

***

***

## Numpy

In [2]:
import numpy as np

In [3]:
x = np.array([25, 2, 5])

In [4]:
y = np.array([0, 1, 2])

***

In [2]:
X = np.array([[25, 2], [5, 26], [3, 7]])

In [3]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X[:, 0]

array([25,  5,  3])

***

## PyTorch

In [1]:
import torch

In [2]:
x_pt = torch.tensor([25, 2, 5])

In [3]:
y_pt = torch.tensor([0, 1, 2])

***

In [2]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])

In [3]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [4]:
X_pt.shape

torch.Size([3, 2])

***

## TensorFlow

In [5]:
import tensorflow as tf

In [7]:
x_tf = tf.Variable([25,2,5])

In [8]:
y_tf = tf.Variable([0,1,2])

***

In [7]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])

In [8]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [10]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

***

### Matplotlib

In [9]:
import matplotlib.pyplot as plt

***

### .DS_Store Files

TRY THIS FIRST (the . deletes files from only the folder)

find .  -name ".DS_Store" -depth -exec rm {} \;