<font size = 8> Basic Tensor Arithmetic

***

In [17]:
# addin or multiplying wiht scalar applies operation to all \
# elements and tensor shape is retained

## Numpy

In [11]:
import numpy as np

In [12]:
X = np.array([[25, 2], [5, 26], [3, 7]])

In [13]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X[:, 0]

array([25,  5,  3])

***

In [14]:
X*2 

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [15]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [18]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

## PyTorch

In [19]:
import torch

In [20]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])

In [21]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [22]:
X_pt.shape

torch.Size([3, 2])

***

In [23]:
X_pt*2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [24]:
X_pt+2

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [25]:
X_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [ ]:
# python operators are overloaded -- could alternatively used torch.mul or torch.add

In [26]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

## TensorFlow

In [5]:
import tensorflow as tf

In [7]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])

In [8]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [10]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

***

In [27]:
X_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [28]:
# you can also use multiple and other operators

In [29]:
tf.add(tf.multiply(X_tf, 2),2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

***

# Hardamard Product

If two tensors have the same size, operations are often by default applied element-wise. This is **not matrix multiplication**, which we'll cover later, but is rather called the **Hadamard product** or simply the **element-wise product**. 

The mathematical notation is $A \odot X$

In [30]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [31]:
A = X+2

In [33]:
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [34]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [35]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [36]:
# element wise multiplication

***

In [37]:
A_pt = X_pt

In [38]:
A_pt + X_pt

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [40]:
A_pt * X_pt

tensor([[625,   4],
        [ 25, 676],
        [  9,  49]])

***

In [39]:
A_tf  = X_tf+2

In [41]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [42]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]], dtype=int32)>