<font size = 8> Basic Tensor Arithmetic

***

In [17]:
# addin or multiplying wiht scalar applies operation to all \
# elements and tensor shape is retained

## Numpy

In [11]:
import numpy as np

In [12]:
X = np.array([[25, 2], [5, 26], [3, 7]])

In [13]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X[:, 0]

array([25,  5,  3])

***

In [14]:
X*2 

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [15]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [18]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

## PyTorch

In [19]:
import torch

In [20]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])

In [21]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [22]:
X_pt.shape

torch.Size([3, 2])

***

In [23]:
X_pt*2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [24]:
X_pt+2

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [25]:
X_pt*2+2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [ ]:
# python operators are overloaded -- could alternatively used torch.mul or torch.add

## TensorFlow

In [5]:
import tensorflow as tf

In [7]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])

In [8]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [10]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>