<font size = 8> Tensor Reduction

***

## Numpy

In [1]:
import numpy as np

In [2]:
X = np.array([[25, 2], [5, 26], [3, 7]])

In [3]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X[:, 0]

array([25,  5,  3])

***

## PyTorch

In [7]:
import torch

ModuleNotFoundError: No module named 'torch'

In [2]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])

In [3]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [4]:
X_pt.shape

torch.Size([3, 2])

***

## TensorFlow

In [8]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [7]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])

In [8]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [10]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>